### ISSUE TITLE
Is project abandoned? Will be here any future?

### ISSUE THREAD

**Issue by greenais** [seigel/pouchdb-react-native#113]
In the latest RN 0.57.5 PDBRN produces warnings for every required plugin (and for pouchdb-core as well), RN claims to depricate cycles by the end of 2018.

```
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle
Require cycle: node_modules\pouchdb-core\node_modules\pouchdb-utils\lib\index-browser.js -> node_modules\pouchdb-core\node_modules\pouchdb-utils\lib\index-browser.js
Require cycle: node_modules\pouchdb-selector-core\node_modules\pouchdb-utils\lib\index-browser.js -> node_modules\pouchdb-selector-core\node_modules\pouchdb-utils\lib\index-browser.js
node_modules\pouchdb-adapter-utils\node_modules\pouchdb-utils\lib\index-browser.js -> node_modules\pouchdb-adapter-utils\node_modules\pouchdb-utils\lib\index-browser.js
Require cycle: node_modules\pouchdb-adapter-asyncstorage\node_modules\pouchdb-utils\lib\index-browser.js -> node_modules\pouchdb-adapter-asyncstorage\node_modules\pouchdb-utils\lib\index-browser.js
Require cycle: node_modules\pouchdb-adapter-http\node_modules\pouchdb-utils\lib\index-browser.js -> node_modules\pouchdb-adapter-http\node_modules\pouchdb-utils\lib\index-browser.js
Require cycle: node_modules\pouchdb-mapreduce-utils\node_modules\pouchdb-utils\lib\index-browser.js -> node_modules\pouchdb-mapreduce-utils\node_modules\pouchdb-utils\lib\index-browser.js
...
```
And this on top of not working queries after replication and less important bugs...

Sole question to author: is there any chance that you will get back to your PDBRN in the nearest future? 
Here is really a lot of brilliant job you've already done and a lot of need in your solution across RN devs, installs speak for themselves.
If I could help somehow - I'll be happy to, let's keep it alive

**Comment by stockulus** [comment]
I am currently in talks with potential future maintainers. I currently not in the position to effort a lot of time. But feel free to change / create pull request etc. I'll try to approve them as fast as possible.

If you want to get a maintainer, just get in contact.

I still love the project and would like to see it continue, but my current focus is web development

Sorry for the inconvenience, but life goes on, and focus shifts

**Comment by greenais** [comment]
Thank you for clearing it out and for all the great job you've done here.
My experience, I'm afraid, won't let me take mantainer's responsibility yet, but I for sure will dig deeper to support project by PRs.
And let you have success on your new web assignments!

**Comment by seigel** [comment]
Any luck finding maintainers sir? What kind of effort does it take for this project?

**Comment by seigel** [comment]
Right.  Well what I will do, is what you suggested above.  I'll try and get familiar with the code and try and attempt some PRs to make things move forward.  Not sure how successful I will be, but I will make an attempt.  Thanks for all your hard work to date.  This is an important package.

**Comment by rdewolff** [comment]
Ping!

**Comment by stockulus** [comment]
still looking for a maintainer to take over.

I am doing more Web and Backend Development at the moment, and do not have that much time left over.

if would spend some time to hand over the Project and would like to see it continued.

**Comment by agape-apps** [comment]
Any updates?

**Comment by stockulus** [comment]
Still looking for a maintainer. I'd recommend to reset up the project and just keep the Adapters.

**Comment by seigel** [comment]
What’s involved in the maintenance?  I might be interested.

**Comment by stockulus** [comment]
The Project did not get the love it needed the last years.

So there is some onetime work to do, other than this is easy. 

I'd be happy to help to get it going

**Comment by rdewolff** [comment]
> The Project did not get the love it needed the last years.

You need to give it more love to get more 💘

**Comment by seigel** [comment]
Sure, I’ll take a run at it.  If I can’t do it well, I will look for another person to give it love :D

**Comment by stockulus** [comment]
if wanted we can do a Video call the next days.

**Comment by seigel** [comment]
Sounds good.  What timezone are you in? And what is your availability over the next while (time of day etc..)

**Comment by stockulus** [comment]
I live in Cologne, so Central Europe Time. Tomorrow evening I am out with old friends. Other than this I have time the next days.

**Comment by seigel** [comment]
Let me figure out some windows. If not are you available next week?

**Comment by stockulus** [comment]
Yes

**Comment by seigel** [comment]
Sorry about that.  We were getting ready for some vacation days.  Are you
available 5pm Tuesday July 27th your time (I believe "today" for you?) or a
bit after?  Any how would you like to chat?  Plus, we should probably get
off the main mailing list, hah!

Cheers
James

**Comment by stockulus** [comment]
Hey James,

that's fine. Is Zoom Ok for you?

**Comment by seigel** [comment]
Yessir

**Comment by stockulus** [comment]
Christoph Stock is inviting you to a scheduled Zoom meeting.

Topic: Christoph Stock's Personal Meeting Room

Join Zoom Meeting
https://us02web.zoom.us/j/5767305366?pwd=MHMya2VGNS8vZHBNWHhCL3hPeWZUdz09

Meeting ID: 576 730 5366
Passcode: 415866

17:00 CET

**Comment by seigel** [comment]
Hello.  I am just working on getting familiar with the space and will hopefully be working on a plan to work on some of the issues and get some updates out.  Bear with me, and submit patches and offer support!  We can't do this alone.
